# Generated by Django 2.0.7 on 2018-07-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
