# Generated by Django 2.0.7 on 2018-07-22 07:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogspost_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
