# Generated by Django 2.0.7 on 2018-07-22 07:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180722_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
